version: "2.2"

volumes:
  minio_storage: { }

services:
  app:
    #    image: 'test-bd:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app_shop
    depends_on:
      - db
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - minio.url=minio
      - minio.accessKey=test
      - minio.secretKey=testStrongPassword
      - minio.bucket-name=myapp
      - minio.secure=false
    cpus: 3
    mem_limit: 1536M

  front:
    image: 'ghcr.io/bizinmitya/front-react-avito:v1.19'
    ports:
      - "3000:3000"
    cpus: 3
    mem_limit: 1536M
  db:
    image: 'postgres:13.1-alpine'
    container_name: db_shop
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    cpus: 3
    mem_limit: 1536M
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testStrongPassword
    command: server --console-address ":9001" /data